name: Hello GitHub Actions 
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: hello
        run: echo "Hello Github Actions"
      - name: show files
        run: ls -la